# NumPy Basics <hr style="border:2.5px solid #126782"></hr>

Data Analyst: Allainah Mae J. Guia <br> Department: Electrical Engineering

In [29]:
# imports and package
import numpy as np
from scipy import stats

# 1D Array

In [19]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [20]:
np.shape(array_a)

(3,)

In [21]:
array_b = np.array([4,5,6])
array_b

array([4, 5, 6])

# 2D Array

In [44]:
my_array = np.array (
    [[1,2,3],[4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
my_array = my_array.T

In [46]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [47]:
# add by row
np.sum(my_array,axis=0)

array([ 6, 15])

In [48]:
# by column
np.sum(my_array,axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [2]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [5]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [6]:
fruits_median = np.median(fruits)
fruits_median

np.float64(120.0)

In [8]:
fruits_sorted = np.sort(fruits)
fruits_sorted

array([ 60,  85, 120, 150, 200])

In [9]:
stats.mode(fruits)

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar vs Panther

# Jaguar

In [30]:
jaguar = np.array ([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [31]:
jag_mean = np.mean(jaguar)
jag_mean

np.float64(9.399999999999999)

In [32]:
jag_median = np.median(jaguar)
jag_median

np.float64(9.8)

In [33]:
jag_mode = stats.mode(jaguar)
jag_mode

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [34]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

np.float64(8.0)

In [35]:
# Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [36]:
# Q2 (median)
q2_jag = np.percentile(jaguar,50)
q2_jag

np.float64(9.8)

In [37]:
# Q3
q3_jag = np.percentile(jaguar,75)
q3_jag

np.float64(10.45)

In [38]:
# IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [39]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

np.float64(4.86)

In [40]:
std_jag = np.std(jaguar,ddof=1)
std_jag

np.float64(2.2045407685048604)

In [41]:
jaguar_sorted =  np.sort(jaguar)
jaguar_sorted

array([ 3. ,  9.1,  9.3,  9.5,  9.8,  9.8, 10.4, 10.4, 10.5, 10.6, 11. ])

# Panther

In [7]:
panther = np.array([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [33]:
pan_mean = np.mean(panther)
pan_mean

np.float64(10.75)

In [49]:
pan_median = np.median(panther)
pan_median

np.float64(9.55)

In [8]:
pan_mode = stats.mode(panther)
pan_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [9]:
max_pan = np.max(panther)
min_pan = np.min(panther)

range_pan = max_pan - min_pan
range_pan

np.float64(10.9)

In [10]:
# Q1
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [11]:
# Q2 (median)
q2_pan = np.percentile(panther,50)
q2_pan

np.float64(9.55)

In [12]:
# Q3
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.625)

In [13]:
# IQR
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)

In [14]:
# sample variance
var_pan = np.var(panther,ddof=1)
var_pan

np.float64(11.082777777777777)

In [15]:
std_pan = np.std(panther,ddof=1)
std_pan

np.float64(3.3290806204983645)

In [42]:
panther_sorted =  np.sort(panther)
panther_sorted

array([ 9.1,  9.1,  9.1,  9.2,  9.2,  9.9, 10.1, 10.8, 11. , 20. ])